apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: my-bridge
  namespace: kafka
spec:
  replicas: 1
  bootstrapServers: kafka-cluster-kafka-bootstrap:9092   # Kafka 클러스터 서비스
  http:
    port: 8080
  consumer:
    config:
      auto.offset.reset: earliest
  producer:
    config: {}

