apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
  annotations:
    strimzi.io/kraft: "enabled"
    strimzi.io/node-pools: "enabled"
spec:
  kafka:
    version: 4.0.0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: loadbalancer
        tls: false
    config:
      auto.create.topics.enable: "false"
      default.replication.factor: 3              # ✅ 브로커 수에 맞춰 조정
      min.insync.replicas: 2                     # ✅ 최소 ISR 2 (실무 환경에 맞춤)
      num.partitions: 6
      log.retention.hours: 72
      offsets.topic.replication.factor: 3        # ✅ 내부 토픽도 2
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 1
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: knp
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  replicas: 3
  roles:
    - broker
    - controller
  resources:
    requests:
      cpu: "1"
      memory: "4Gi"
    limits:
      cpu: "1.5"
      memory: "4Gi"
  storage:
    type: persistent-claim
    class: local-storage
    size: 50Gi
    deleteClaim: false
